{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "186461b0-a0e0-43c0-b158-d0072be4975d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "from datetime import datetime\n",
    "\n",
    "model = joblib.load(\"fraud_detection_pipeline.pkl\")\n",
    "\n",
    "if \"fraud_alerts\" not in st.session_state:\n",
    "    st.session_state.fraud_alerts = []\n",
    "\n",
    "st.title(\"Fraud Detection Prediction App\")\n",
    "st.markdown(\"Please enter the transaction details and use the predict button\")\n",
    "st.divider()\n",
    "\n",
    "col_form, col_alerts = st.columns([2, 1])\n",
    "\n",
    "with col_form:\n",
    "    transaction_type = st.selectbox(\"Transaction Type\", [\"PAYMENT\", \"TRANSFER\", \"CASH_OUT\", \"DEPOSIT\"])\n",
    "    amount = st.number_input(\"Amount\", min_value=0.0, value=1000.0)\n",
    "\n",
    "    oldbalanceOrg = st.number_input(\"Old Balance (Sender)\", min_value=0.0, value=10000.0)\n",
    "    newbalanceOrig = st.number_input(\"New Balance (Sender)\", min_value=0.0, value=9000.0)\n",
    "    oldbalanceDest = st.number_input(\"Old Balance (Receiver)\", min_value=0.0, value=0.0)\n",
    "    newbalanceDest = st.number_input(\"New Balance (Receiver)\", min_value=0.0, value=0.0)\n",
    "\n",
    "    if st.button(\"Predict\"):\n",
    "        input_data = pd.DataFrame([{\n",
    "            \"type\": transaction_type,\n",
    "            \"amount\": amount,\n",
    "            \"oldbalanceOrg\": oldbalanceOrg,\n",
    "            \"newbalanceOrig\": newbalanceOrig,\n",
    "            \"oldbalanceDest\": oldbalanceDest,\n",
    "            \"newbalanceDest\": newbalanceDest\n",
    "        }])\n",
    "\n",
    "        prediction = model.predict(input_data)[0]\n",
    "\n",
    "        st.subheader(f\"Prediction: '{int(prediction)}'\")\n",
    "\n",
    "        if prediction == 1:\n",
    "            st.error(\"This transaction can be fraud\")\n",
    "            st.toast(\"Fraudulent transaction detected!\", icon=\"🚨\")\n",
    "            st.session_state.fraud_alerts.insert(0, {\n",
    "                \"Time\": datetime.now().strftime(\"%H:%M:%S\"),\n",
    "                \"Type\": transaction_type,\n",
    "                \"Amount\": amount,\n",
    "                \"Sender Old Bal\": oldbalanceOrg,\n",
    "                \"Sender New Bal\": newbalanceOrig,\n",
    "            })\n",
    "        else:\n",
    "            st.success(\"This transaction looks legit\")\n",
    "\n",
    "with col_alerts:\n",
    "    st.subheader(\"🚨 Fraud Alerts\")\n",
    "    alert_count = len(st.session_state.fraud_alerts)\n",
    "    st.metric(\"Flagged this session\", alert_count)\n",
    "\n",
    "    if alert_count == 0:\n",
    "        st.info(\"No fraudulent transactions detected yet.\")\n",
    "    else:\n",
    "        for alert in st.session_state.fraud_alerts:\n",
    "            st.warning(\n",
    "                f\"**{alert['Time']}** — {alert['Type']} of \"\n",
    "                f\"${alert['Amount']:,.2f} flagged as fraud\"\n",
    "            )\n",
    "        if st.button(\"Clear alerts\"):\n",
    "            st.session_state.fraud_alerts = []\n",
    "            st.rerun()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8d78b10-215b-412a-bd10-ef05ed712c12",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
